//
//  QuestionsData.swift
//  JDAM
//
//  Created by Dmitry Volkov on 11/02/2025.
//

import Foundation

struct Question {
    let question: String
    let category: QuestionCategory
}

struct QuestionsData {
    var data = [
        Question(question: "Какое самое странное блюдо вы когда-либо пробовали?", category: .live),
        Question(question: "Если бы вы могли стать любым животным на день, кем бы вы стали и почему?", category: .live),
        Question(question: "Какая самая нелепая вещь, которую вы делали в детстве?", category: .live),
        Question(question: "Если бы ваша жизнь была фильмом, как бы он назывался?", category: .live),
        Question(question: "Какая самая странная привычка у вас есть?", category: .live),
        Question(question: "Если бы вы могли поменяться местами с любым человеком на день, кого бы вы выбрали?", category: .live),
        Question(question: "Какая самая смешная ситуация произошла с вами в общественном месте?", category: .live),
        Question(question: "Если бы вы могли добавить одно правило в мире, какое бы это было?", category: .live),
        Question(question: "Какая самая странная вещь, которую вы когда-либо покупали?", category: .live),
        Question(question: "Если бы вы могли создать новый праздник, как бы он назывался и как бы его отмечали?", category: .live),
        Question(question: "Какая самая неловкая ситуация произошла с вами на свидании?", category: .live),
        Question(question: "Если бы вы могли выбрать себе суперспособность, но оно должно быть совершенно бесполезным, что бы это было?", category: .live),
        Question(question: "Какая самая странная вещь, которую вы когда-либо ели в 2 часа ночи?", category: .live),
        Question(question: "Если бы вы могли создать свою собственную пиццу, какие бы ингредиенты вы добавили?", category: .live),
        Question(question: "Какая самая смешная шутка, которую вы когда-либо слышали?", category: .live),
        Question(question: "Если бы вы могли жить в любой вымышленной вселенной, какую бы вы выбрали?", category: .live),
        Question(question: "Какая самая странная вещь, которую вы когда-либо делали, чтобы избежать работы?", category: .live),
        Question(question: "Если бы вы могли создать свой собственный смайлик, как бы он выглядел?", category: .live),
        Question(question: "Какая самая нелепая вещь, которую вы когда-либо говорили вслух?", category: .live),
        Question(question: "Если бы вы могли выбрать себе новое имя, какое бы вы выбрали и почему?", category: .live),
        
        Question(question: "Какое самое необычное хобби у вас есть или было?", category: .sportHobby),
        Question(question: "Если бы вы могли стать профессиональным спортсменом, какой вид спорта вы бы выбрали?", category: .sportHobby),
        Question(question: "Какое самое странное спортивное событие вы когда-либо видели?", category: .sportHobby),
        Question(question: "Если бы вы могли создать новый вид спорта, как бы он назывался и в чем бы заключался?", category: .sportHobby),
        Question(question: "Какое самое нелепое хобби вы можете придумать?", category: .sportHobby),
        Question(question: "Если бы вы могли тренироваться с любым спортсменом в мире, кого бы вы выбрали?", category: .sportHobby),
        Question(question: "Какое самое странное спортивное снаряжение вы когда-либо использовали?", category: .sportHobby),
        Question(question: "Если бы вы могли добавить один новый вид спорта в Олимпийские игры, что бы это было?", category: .sportHobby),
        Question(question: "Какое самое необычное хобби вы хотели бы попробовать?", category: .sportHobby),
        Question(question: "Если бы вы могли стать чемпионом мира в любом виде спорта, в каком бы вы хотели?", category: .sportHobby),
        Question(question: "Какое самое странное спортивное правило вы знаете?", category: .sportHobby),
        Question(question: "Если бы вы могли создать свою собственную спортивную команду, как бы она называлась?", category: .sportHobby),
        Question(question: "Какое самое нелепое хобби вы когда-либо слышали от друзей?", category: .sportHobby),
        Question(question: "Если бы вы могли изобрести новый спортивный инвентарь, что бы это было?", category: .sportHobby),
        Question(question: "Какое самое странное спортивное соревнование вы хотели бы посетить?", category: .sportHobby),
        Question(question: "Если бы вы могли стать тренером любой команды, какую бы вы выбрали?", category: .sportHobby),
        Question(question: "Какое самое необычное хобби вы могли бы сделать популярным?", category: .sportHobby),
        Question(question: "Если бы вы могли добавить один новый вид спорта в школьную программу, что бы это было?", category: .sportHobby),
        Question(question: "Какое самое странное спортивное прозвище вы слышали?", category: .sportHobby),
        Question(question: "Если бы вы могли создать свою собственную спортивную лигу, какие правила в ней были бы?", category: .sportHobby),
        
        Question(question: "Если бы вы могли поужинать с любой знаменитостью, кого бы вы выбрали и почему?", category: .celebrities),
        Question(question: "Какая знаменитость, по вашему мнению, самая переоцененная?", category: .celebrities),
        Question(question: "Если бы вы могли поменяться местами с любой знаменитостью на день, кого бы вы выбрали?", category: .celebrities),
        Question(question: "Какая знаменитость, по вашему мнению, самая недооцененная?", category: .celebrities),
        Question(question: "Если бы вы могли стать лучшим другом любой знаменитости, кто бы это был?", category: .celebrities),
        Question(question: "Какая знаменитость, по вашему мнению, имеет самое странное хобби?", category: .celebrities),
        Question(question: "Если бы вы могли снять фильм с любой знаменитостью в главной роли, кого бы вы выбрали?", category: .celebrities),
        Question(question: "Какая знаменитость, по вашему мнению, самая забавная?", category: .celebrities),
        Question(question: "Если бы вы могли задать любой вопрос знаменитости, что бы вы спросили?", category: .celebrities),
        Question(question: "Какая знаменитость, по вашему мнению, самая стильная?", category: .celebrities),
        Question(question: "Если бы вы могли стать менеджером любой знаменитости, кого бы вы выбрали?", category: .celebrities),
        Question(question: "Какая знаменитость, по вашему мнению, самая талантливая?", category: .celebrities),
        Question(question: "Если бы вы могли создать дуэт с любой знаменитостью, кто бы это был?", category: .celebrities),
        Question(question: "Какая знаменитость, по вашему мнению, самая загадочная?", category: .celebrities),
        Question(question: "Если бы вы могли снять реалити-шоу с любой знаменитостью, кто бы это был?", category: .celebrities),
        Question(question: "Какая знаменитость, по вашему мнению, самая влиятельная?", category: .celebrities),
        Question(question: "Если бы вы могли стать соседом любой знаменитости, кого бы вы выбрали?", category: .celebrities),
        Question(question: "Какая знаменитость, по вашему мнению, самая эксцентричная?", category: .celebrities),
        Question(question: "Если бы вы могли создать группу с любыми знаменитостями, кто бы в нее входил?", category: .celebrities),
        Question(question: "Какая знаменитость, по вашему мнению, самая вдохновляющая?", category: .celebrities),
        
        Question(question: "Если бы вы могли сыграть любую роль в любом фильме, какую бы вы выбрали?", category: .artCinema),
        Question(question: "Какой фильм, по вашему мнению, самый переоцененный?", category: .artCinema),
        Question(question: "Если бы вы могли создать свой собственный фильм, о чем бы он был?", category: .artCinema),
        Question(question: "Какой фильм, по вашему мнению, самый недооцененный?", category: .artCinema),
        Question(question: "Если бы вы могли стать режиссером любого фильма, какой бы это был фильм?", category: .artCinema),
        Question(question: "Какой фильм, по вашему мнению, имеет самый неожиданный сюжет?", category: .artCinema),
        Question(question: "Если бы вы могли добавить любого актера в уже существующий фильм, кого бы вы выбрали и в какую роль?", category: .artCinema),
        Question(question: "Какой фильм, по вашему мнению, самый забавный?", category: .artCinema),
        Question(question: "Если бы вы могли задать любой вопрос режиссеру или актеру, что бы вы спросили?", category: .artCinema),
        Question(question: "Какой фильм, по вашему мнению, самый стильный?", category: .artCinema),
        Question(question: "Если бы вы могли стать продюсером любого фильма, какой бы это был фильм?", category: .artCinema),
        Question(question: "Какой фильм, по вашему мнению, самый талантливый?", category: .artCinema),
        Question(question: "Если бы вы могли создать дуэт актеров для фильма, кто бы это был?", category: .artCinema),
        Question(question: "Какой фильм, по вашему мнению, самый загадочный?", category: .artCinema),
        Question(question: "Если бы вы могли снять документальный фильм о любой знаменитости, кто бы это был?", category: .artCinema),
        Question(question: "Какой фильм, по вашему мнению, самый влиятельный?", category: .artCinema),
        Question(question: "Если бы вы могли стать соседом любой знаменитости из мира кино, кого бы вы выбрали?", category: .artCinema),
        Question(question: "Какой фильм, по вашему мнению, самый эксцентричный?", category: .artCinema),
        Question(question: "Если бы вы могли создать группу актеров для фильма, кто бы в нее входил?", category: .artCinema),
        Question(question: "Какой фильм, по вашему мнению, самый вдохновляющий?", category: .artCinema),
        
        Question(question: "Какое самое нелепое супергеройское имя можно придумать?", category: .other),
        Question(question: "Если бы ты мог добавить один странный закон в Конституцию, какой бы он был?", category: .other),
        Question(question: "Какой предмет в школе точно должен быть, но его почему-то нет?", category: .other),
        Question(question: "Какой заголовок газет мог бы лучше всего описать твой день?", category: .other),
        Question(question: "Какое нелепое заклинание мог бы придумать неуклюжий волшебник?", category: .other),
        Question(question: "Если бы люди могли менять цвет, как хамелеоны, в каких ситуациях это было бы полезно?", category: .other),
        Question(question: "Какой самый странный способ приветствия ты мог бы придумать?", category: .other),
        Question(question: "Если бы бытовая техника могла разговаривать, о чем бы она жаловалась больше всего?", category: .other),
        Question(question: "Какое самое нелепое место для проведения Олимпийских игр можно придумать?", category: .other),
        Question(question: "Какой самый неожиданный предмет можно было бы добавить в комплект новогоднего подарка?", category: .other),
        Question(question: "Какой предмет мебели точно должен быть живым и уметь разговаривать?", category: .other),
        Question(question: "Какую самую странную фобию можно придумать?", category: .other),
        Question(question: "Если бы животные могли работать в офисе, кто кем бы стал?", category: .other),
        Question(question: "Какой фильм можно пересказать в одном предложении, чтобы он звучал максимально нелепо?", category: .other),
        Question(question: "Если бы можно было открыть ресторан с самой странной концепцией, что бы там подавали?", category: .other),
        Question(question: "Какое животное могло бы стать самым неожиданным домашним питомцем?", category: .other),
        Question(question: "Если бы ты мог добавить один новый праздник в календарь, что бы это был за день?", category: .other),
        Question(question: "Какой самый абсурдный рекорд можно установить в книге рекордов Гиннесса?", category: .other),
        Question(question: "Какой суперспособностью точно нельзя было бы пользоваться в общественных местах?", category: .other),
        Question(question: "Какой самый неожиданный подарок можно подарить на день рождения?", category: .other),
        
        Question(question: "Какое животное могло бы стать президентом леса?", category: .nature),
        Question(question: "Если бы деревья могли говорить, о чем бы они больше всего жаловались?", category: .nature),
        Question(question: "Какой суперспособностью должна обладать рыба, чтобы стать королем океана?", category: .nature),
        Question(question: "Какое насекомое, по-твоему, мечтает о карьере в Голливуде?", category: .nature),
        Question(question: "Какое природное явление могло бы быть супергероем и какое у него было бы имя?", category: .nature),
        Question(question: "Какое растение могло бы стать звездой ТикТока и за что?", category: .nature),
        Question(question: "Если бы грибы могли ходить, куда бы они отправились первыми?", category: .nature),
        Question(question: "Какое животное лучше всех умеет устраивать вечеринки в джунглях?", category: .nature),
        Question(question: "Какой цветок самый романтичный и почему?", category: .nature),
        Question(question: "Если бы медведи умели готовить, какое блюдо стало бы их фирменным?", category: .nature),
        Question(question: "Какой зверь мог бы быть лучшим комиком и почему?", category: .nature),
        Question(question: "Какое природное явление могло бы стать музыкальным хитом?", category: .nature),
        Question(question: "Если бы ураганы носили клички животных, какое название было бы самым подходящим?", category: .nature),
        Question(question: "Какой фрукт мог бы возглавить армию здорового питания?", category: .nature),
        Question(question: "Какое животное выглядело бы лучше всего в очках?", category: .nature),
        Question(question: "Какой обитатель леса мог бы стать детективом?", category: .nature),
        Question(question: "Какое животное лучше всех справилось бы с работой таксиста?", category: .nature),
        Question(question: "Какое существо океана могло бы стать ведущим вечернего шоу?", category: .nature),
        Question(question: "Какой цветок мог бы стать героем мультфильма и о чем был бы сюжет?", category: .nature),
        Question(question: "Какой зверь стал бы лучшим преподавателем в школе леса?", category: .nature)
    ]
}
