//
//  QuestionsData.swift
//  JDAM
//
//  Created by Dmitry Volkov on 11/02/2025.
//

import Foundation

struct Question {
    let question: String
    let answer: String
    let category: QuestionCategory
}

struct QuestionsData {
    var data = [
        Question(question: "Как называется самая известная книга о смысле жизни, написанная Виктором Франклом?", answer: "Человек в поисках смысла", category: .live),
        Question(question: "Какой фильм считается самым кассовым в истории кинематографа?", answer: "Аватар", category: .live),
        Question(question: "Как называется самая популярная социальная сеть в мире?", answer: "Facebook", category: .live),
        Question(question: "Какое самое распространенное имя в мире?", answer: "Мухаммед", category: .live),
        Question(question: "Как называется самая известная статуя в мире, символизирующая свободу?", answer: "Статуя Свободы", category: .live),
        Question(question: "Какой город считается самым густонаселенным в мире?", answer: "Токио", category: .live),
        Question(question: "Как называется самая длинная река в мире?", answer: "Амазонка", category: .live),
        Question(question: "Какой самый популярный вид спорта в мире?", answer: "Футбол", category: .live),
        Question(question: "Как называется самая известная картина Леонардо да Винчи?", answer: "Мона Лиза", category: .live),
        Question(question: "Какой самый популярный напиток в мире после воды?", answer: "Чай", category: .live),
        Question(question: "Как называется самая высокая гора в мире?", answer: "Эверест", category: .live),
        Question(question: "Какой самый популярный музыкальный жанр в мире?", answer: "Поп-музыка", category: .live),
        Question(question: "Как называется самая известная поисковая система в интернете?", answer: "Google", category: .live),
        Question(question: "Какой самый популярный праздник в мире?", answer: "Новый год", category: .live),
        Question(question: "Как называется самая известная книга, написанная Джорджем Оруэллом, о тоталитарном обществе?", answer: "1984", category: .live),
        Question(question: "Какой самый популярный фрукт в мире?", answer: "Банан", category: .live),
        Question(question: "Как называется самая известная космическая программа, которая отправила человека на Луну?", answer: "Аполлон", category: .live),
        Question(question: "Какой самый популярный вид домашнего животного в мире?", answer: "Собака", category: .live),
        Question(question: "Как называется самая известная достопримечательность в Индии?", answer: "Тадж-Махал", category: .live),
        Question(question: "Какой самый популярный фильм о супергероях за всю историю?", answer: "Мстители: Финал", category: .live),
        
        Question(question: "Какой вид спорта называют 'королевой спорта'?", answer: "Легкая атлетика", category: .sportHobby),
        Question(question: "Какое хобби связано с созданием изображений с помощью красок и кистей?", answer: "Живопись", category: .sportHobby),
        Question(question: "Какой вид спорта включает в себя элементы гимнастики, танцев и акробатики?", answer: "Художественная гимнастика", category: .sportHobby),
        Question(question: "Какое хобби связано с выращиванием растений и уходом за садом?", answer: "Садоводство", category: .sportHobby),
        Question(question: "Какой вид спорта является национальным в Японии?", answer: "Сумо", category: .sportHobby),
        Question(question: "Какое хобби связано с созданием украшений из бисера и бусин?", answer: "Бисероплетение", category: .sportHobby),
        Question(question: "Какой вид спорта включает в себя катание на доске по волнам?", answer: "Серфинг", category: .sportHobby),
        Question(question: "Какое хобби связано с коллекционированием монет?", answer: "Нумизматика", category: .sportHobby),
        Question(question: "Какой вид спорта связан с игрой в мяч через сетку на пляже?", answer: "Пляжный волейбол", category: .sportHobby),
        Question(question: "Какое хобби связано с созданием моделей самолетов, кораблей или автомобилей?", answer: "Моделирование", category: .sportHobby),
        Question(question: "Какой вид спорта включает в себя стрельбу из лука?", answer: "Стрельба из лука", category: .sportHobby),
        Question(question: "Какое хобби связано с приготовлением блюд разных кухонь мира?", answer: "Кулинария", category: .sportHobby),
        Question(question: "Какой вид спорта связан с катанием на коньках по льду?", answer: "Фигурное катание", category: .sportHobby),
        Question(question: "Какое хобби связано с созданием изделий из глины?", answer: "Гончарное дело", category: .sportHobby),
        Question(question: "Какой вид спорта включает в себя прыжки с парашютом?", answer: "Парашютный спорт", category: .sportHobby),
        Question(question: "Какое хобби связано с изучением и наблюдением за звездами?", answer: "Астрономия", category: .sportHobby),
        Question(question: "Какой вид спорта связан с игрой в мяч на льду?", answer: "Хоккей", category: .sportHobby),
        Question(question: "Какое хобби связано с созданием музыки с помощью компьютера?", answer: "Музыкальное продюсирование", category: .sportHobby),
        Question(question: "Какой вид спорта включает в себя бег по пересеченной местности?", answer: "Кросс", category: .sportHobby),
        Question(question: "Какое хобби связано с созданием украшений из проволоки и камней?", answer: "Ювелирное дело", category: .sportHobby),
        
        Question(question: "Кто является самым высокооплачиваемым актером в мире по версии Forbes 2023 года?", answer: "Дуэйн Джонсон", category: .celebrities),
        Question(question: "Какая певица известна как 'Королева поп-музыки'?", answer: "Мадонна", category: .celebrities),
        Question(question: "Кто сыграл главную роль в фильме 'Титаник'?", answer: "Леонардо ДиКаприо", category: .celebrities),
        Question(question: "Какой актер известен своей ролью Железного человека в киновселенной Marvel?", answer: "Роберт Дауни-младший", category: .celebrities),
        Question(question: "Кто является самым популярным певцом в мире по количеству подписчиков в Spotify?", answer: "The Weeknd", category: .celebrities),
        Question(question: "Какая актриса сыграла Гермиону Грейнджер в фильмах о Гарри Поттере?", answer: "Эмма Уотсон", category: .celebrities),
        Question(question: "Кто является режиссером фильма 'Начало' и 'Интерстеллар'?", answer: "Кристофер Нолан", category: .celebrities),
        Question(question: "Какая певица известна своими хитами 'Bad Guy' и 'Therefore I Am'?", answer: "Билли Айлиш", category: .celebrities),
        Question(question: "Кто сыграл Джокера в фильме 2019 года?", answer: "Хоакин Феникс", category: .celebrities),
        Question(question: "Какая актриса получила 'Оскар' за роль в фильме 'Ла-Ла Ленд', но награду вручили по ошибке?", answer: "Эмма Стоун", category: .celebrities),
        Question(question: "Кто является основателем компании Tesla и SpaceX?", answer: "Илон Маск", category: .celebrities),
        Question(question: "Какая певица известна как 'Мать-монстр'?", answer: "Леди Гага", category: .celebrities),
        Question(question: "Кто сыграл главную роль в сериале 'Шерлок'?", answer: "Бенедикт Камбербэтч", category: .celebrities),
        Question(question: "Какая актриса известна своей ролью в фильмах 'Голодные игры'?", answer: "Дженнифер Лоуренс", category: .celebrities),
        Question(question: "Кто является самым молодым лауреатом Нобелевской премии мира?", answer: "Малала Юсуфзай", category: .celebrities),
        Question(question: "Какая певица известна своими хитами 'Rolling in the Deep' и 'Hello'?", answer: "Адель", category: .celebrities),
        Question(question: "Кто сыграл Тони Монтану в фильме 'Лицо со шрамом'?", answer: "Аль Пачино", category: .celebrities),
        Question(question: "Какая актриса известна своей ролью в фильмах 'Пираты Карибского моря'?", answer: "Кира Найтли", category: .celebrities),
        Question(question: "Кто является самым популярным блогером на YouTube по количеству подписчиков?", answer: "Мистер Бист (MrBeast)", category: .celebrities),
        Question(question: "Какая певица известна своими хитами 'Shake It Off' и 'Blank Space'?", answer: "Тейлор Свифт", category: .celebrities),
        
        Question(question: "Какой фильм получил больше всего наград 'Оскар' за всю историю?", answer: "Титаник, Властелин колец: Возвращение короля, Бен-Гур", category: .artCinema),
        Question(question: "Кто написал картину 'Мона Лиза'?", answer: "Леонардо да Винчи", category: .artCinema),
        Question(question: "Какой фильм считается самым кассовым в истории кинематографа?", answer: "Аватар", category: .artCinema),
        Question(question: "Кто является режиссером фильма 'Крестный отец'?", answer: "Фрэнсис Форд Коппола", category: .artCinema),
        Question(question: "Какой художник известен своими картинами в стиле кубизм?", answer: "Пабло Пикассо", category: .artCinema),
        Question(question: "Какой фильм стал первым полнометражным анимационным фильмом Disney?", answer: "Белоснежка и семь гномов", category: .artCinema),
        Question(question: "Кто написал картину 'Звездная ночь'?", answer: "Винсент Ван Гог", category: .artCinema),
        Question(question: "Какой фильм считается первым в истории звуковым кино?", answer: "Певец джаза", category: .artCinema),
        Question(question: "Кто является автором скульптуры 'Давид'?", answer: "Микеланджело", category: .artCinema),
        Question(question: "Какой фильм стал первым, получившим 'Оскар' за лучший фильм?", answer: "Крылья", category: .artCinema),
        Question(question: "Кто написал картину 'Крик'?", answer: "Эдвард Мунк", category: .artCinema),
        Question(question: "Какой фильм считается первым в истории цветным?", answer: "Унесенные ветром", category: .artCinema),
        Question(question: "Кто является режиссером фильма 'Психо'?", answer: "Альфред Хичкок", category: .artCinema),
        Question(question: "Какой художник известен своими картинами в стиле сюрреализм?", answer: "Сальвадор Дали", category: .artCinema),
        Question(question: "Какой фильм стал первым, получившим 'Оскар' за лучший анимационный фильм?", answer: "Шрек", category: .artCinema),
        Question(question: "Кто написал картину 'Герника'?", answer: "Пабло Пикассо", category: .artCinema),
        Question(question: "Какой фильм считается первым в истории 3D-кино?", answer: "Аватар", category: .artCinema),
        Question(question: "Кто является автором скульптуры 'Мыслитель'?", answer: "Огюст Роден", category: .artCinema),
        Question(question: "Какой фильм стал первым, получившим 'Оскар' за лучший международный фильм?", answer: "Мамаша Кураж и ее дети", category: .artCinema),
        Question(question: "Кто написал картину 'Девушка с жемчужной сережкой'?", answer: "Ян Вермеер", category: .artCinema),
        
        Question(question: "Какое самое глубокое озеро в мире?", answer: "Байкал", category: .other),
        Question(question: "Какой язык является самым распространенным в мире по числу носителей?", answer: "Китайский", category: .other),
        Question(question: "Какое животное является самым крупным на Земле?", answer: "Синий кит", category: .other),
        Question(question: "Какой город считается самым древним из постоянно населенных?", answer: "Иерихон", category: .other),
        Question(question: "Какая планета Солнечной системы самая горячая?", answer: "Венера", category: .other),
        Question(question: "Какой самый популярный вид чая в мире?", answer: "Черный чай", category: .other),
        Question(question: "Какое самое маленькое государство в мире?", answer: "Ватикан", category: .other),
        Question(question: "Какой самый длинный мост в мире?", answer: "Даньян-Куньшаньский виадук", category: .other),
        Question(question: "Какое самое быстрое наземное животное?", answer: "Гепард", category: .other),
        Question(question: "Какой самый популярный вид кофе в мире?", answer: "Эспрессо", category: .other),
        Question(question: "Какая самая высокая гора в Африке?", answer: "Килиманджаро", category: .other),
        Question(question: "Какой самый популярный вид хлеба в мире?", answer: "Пшеничный хлеб", category: .other),
        Question(question: "Какое самое большое по площади государство в мире?", answer: "Россия", category: .other),
        Question(question: "Какой самый популярный вид спорта в Азии?", answer: "Крикет", category: .other),
        Question(question: "Какая самая длинная река в Европе?", answer: "Волга", category: .other),
        Question(question: "Какой самый популярный вид пиццы в мире?", answer: "Маргарита", category: .other),
        Question(question: "Какое самое маленькое млекопитающее в мире?", answer: "Свиноносая летучая мышь", category: .other),
        Question(question: "Какой самый популярный вид мороженого в мире?", answer: "Ванильное", category: .other),
        Question(question: "Какая самая высокая гора в Южной Америке?", answer: "Аконкагуа", category: .other),
        Question(question: "Какой самый популярный вид сыра в мире?", answer: "Чеддер", category: .other),
        
        Question(question: "Какое самое высокое дерево в мире?", answer: "Секвойя", category: .nature),
        Question(question: "Какое животное является символом Австралии?", answer: "Кенгуру", category: .nature),
        Question(question: "Какой океан является самым большим по площади?", answer: "Тихий океан", category: .nature),
        Question(question: "Какое самое быстрое морское животное?", answer: "Парусник", category: .nature),
        Question(question: "Какой водопад считается самым высоким в мире?", answer: "Анхель", category: .nature),
        Question(question: "Какое растение является самым большим в мире?", answer: "Гигантская секвойя", category: .nature),
        Question(question: "Какое животное является самым крупным на суше?", answer: "Африканский слон", category: .nature),
        Question(question: "Какой материк является самым сухим на Земле?", answer: "Антарктида", category: .nature),
        Question(question: "Какое животное может спать до 22 часов в сутки?", answer: "Коала", category: .nature),
        Question(question: "Какой цветок считается самым большим в мире?", answer: "Раффлезия", category: .nature),
        Question(question: "Какое животное является самым ядовитым в мире?", answer: "Кубомедуза", category: .nature),
        Question(question: "Какой лес является самым большим в мире?", answer: "Амазонский тропический лес", category: .nature),
        Question(question: "Какое животное может менять цвет кожи?", answer: "Хамелеон", category: .nature),
        Question(question: "Какой вулкан является самым активным в мире?", answer: "Килауэа", category: .nature),
        Question(question: "Какое животное является самым маленьким в мире?", answer: "Карликовая многозубка", category: .nature),
        Question(question: "Какой остров является самым большим в мире?", answer: "Гренландия", category: .nature),
        Question(question: "Какое животное может прожить дольше всех без воды?", answer: "Верблюд", category: .nature),
        Question(question: "Какой цветок считается самым маленьким в мире?", answer: "Вольфия", category: .nature),
        Question(question: "Какое животное является самым быстрым в воде?", answer: "Парусник", category: .nature),
        Question(question: "Какой материк является самым влажным на Земле?", answer: "Южная Америка", category: .nature)
    ]
}
